const fs = require('fs');
const path = require('path');

// Read BACKEND_URL or API_URL from environment variables
const rawBackendUrl = process.env.BACKEND_URL || process.env.API_URL || 'http://localhost:3000';

// Remove trailing slash if present, to be consistent
const cleanBackendUrl = rawBackendUrl.replace(/\/$/, '');

// If it already ends with /api, use it as is; otherwise append /api
const apiUrl = cleanBackendUrl.endsWith('/api') ? cleanBackendUrl : `${cleanBackendUrl}/api`;

const envDirectory = path.join(__dirname, 'src', 'environments');
const envFilePath = path.join(envDirectory, 'environment.ts');

const envFileContent = `// This file is auto-generated by set-env.js at build time
export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

try {
  // Ensure the directory exists
  if (!fs.existsSync(envDirectory)) {
    fs.mkdirSync(envDirectory, { recursive: true });
  }

  // Write the environment file
  fs.writeFileSync(envFilePath, envFileContent, { encoding: 'utf8' });
  console.log(`[set-env.js] Successfully generated environment.ts with apiUrl: ${apiUrl}`);
} catch (error) {
  console.error('[set-env.js] Error writing environment.ts file:', error);
  process.exit(1);
}
